crates/contracts/ab-contract-example/src/lib.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-macros/src/contract.rs, crates/contracts/ab-contracts-macros/src/contract/init.rs, crates/contracts/ab-contracts-macros/src/contract/methods.rs, crates/contracts/ab-contracts-macros/src/lib.rs
=> Rename `#[constructor]` to `#[init]`

crates/contracts/ab-contract-example/src/lib.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-io-type/src/lib.rs, crates/contracts/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/ab-contracts-io-type/src/trivial_type.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-macros/src/contract/methods.rs, crates/contracts/ab-contracts-macros/src/contract/view.rs, crates/contracts/ab-contracts-macros/src/lib.rs
Two big changes here.
First, return type can only be `TrivialType` now, for variable size types `#[result]` must be used.
Second, `CAPACITY` is no longer a constant, but rather a dynamic parameter. `VariableBytes` still has a constant in it now called `RECOMMENDED_ALLOCATION` to allow host to call into methods with variable size outputs since it needs to know how much memory to allocate, but it is now possible for host or another contract to provide more or less than `RECOMMENDED_ALLOCATION` if necessary.
=> Rework variable size data handing

crates/contracts/ab-contract-example/src/lib.rs, crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-macros/src/contract.rs, crates/contracts/ab-contracts-macros/src/contract/methods.rs, crates/contracts/ab-contracts-macros/src/contract/update.rs, crates/contracts/ab-contracts-macros/src/lib.rs
This renames `#[call]` to `#[update]` for consistency in terminology and to reduce confusion. Similarly `Env::invoke()` is renamed to `Env::call()`.
The bigger change here is usage of a bit esoteric `self: &&mut Env` for non-`#[view]` methods that allows to both share `&Env` as such, but still prevents calling non-`#[view]` methods from `#[view]` methods through helper methods.
Some smaller improvements: `Env::origin()` as replaced with `Env::context()` and `Env::caller()`. Context is for context under which operations are happening, meaning token transfers from "Context" contract are typically allowed, while `Env::caller()` is the previous contract in call stack. `Address::NOBODY` is introduced as a sentinel value for these purposes.
=> Environment improvements

crates/contracts/ab-contract-example/src/lib.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-io-type/src/lib.rs, crates/contracts/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-macros/src/contract.rs, crates/contracts/ab-contracts-macros/src/contract/init.rs, crates/contracts/ab-contracts-macros/src/contract/methods.rs, crates/contracts/ab-contracts-macros/src/contract/update.rs, crates/contracts/ab-contracts-macros/src/lib.rs
First of all this provides safe constructors for `MaybeData` and `VariableBytes`, which are handy for calls into smart contracts.
Second, `#[tmp]` argument is now supported that allows contract to store auxiliary information while processing a transaction. For example it is possible to make a call into contract to approve balance transfer and then another contract with `Address::NOBODY` context would still be able to enact the transfer on behalf of the contract that approved transfer earlier in transaction processing. This should allow for fairly creative workflows.
=> Contracts upgrades

Cargo.lock, crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-system-contract-address-allocator/Cargo.toml, crates/contracts/ab-system-contract-address-allocator/src/lib.rs, crates/contracts/ab-system-contract-code/Cargo.toml, crates/contracts/ab-system-contract-code/src/lib.rs
This introduces first 2 system contract that should in theory be sufficient to deploy contracts.
One is responsible for per-shard address allocations and another manages code of contracts in its slot.
=> First system contracts

crates/contracts/ab-contracts-io-type/src/lib.rs, crates/contracts/ab-contracts-trivial-type-derive/src/lib.rs
This will make things more compact than they are right now, also, technically (from binary layout point of view) structs with fields can be encoded as tuple structs to skip field names completely and struct/enum names/enum variants names can have 0 length, compressing them too, resulting in very compact description of the binary layout of the data structures
=> Optimize metadata of tuple structs and similar enum variants

crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-io-type/src/lib.rs, crates/contracts/ab-contracts-io-type/src/trivial_type.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-macros/src/contract.rs, crates/contracts/ab-contracts-macros/src/contract/methods.rs, crates/contracts/ab-contracts-trivial-type-derive/src/lib.rs
This prepares for trait support where `CONTRACT_METADATA` section will contain not a single static of main contract implementation, but also other statics corresponding to various implemented traits.
Contract's main metadata now starts with `ContractMetadataKind::Contract` to distinguish from trait metadata.
=> Metadata tweaks

crates/contracts/ab-contract-example/src/lib.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-macros/src/contract/init.rs, crates/contracts/ab-contracts-macros/src/contract/methods.rs, crates/contracts/ab-contracts-macros/src/contract/update.rs, crates/contracts/ab-contracts-macros/src/contract/view.rs, crates/contracts/ab-contracts-macros/src/lib.rs, crates/contracts/ab-system-contract-address-allocator/src/lib.rs, crates/contracts/ab-system-contract-code/src/lib.rs
This splits large method into several that should help when implementing trait support.
There are also some cleanups and TODOs there as well.
=> Contract macro refactoring

Cargo.lock, crates/contracts/ab-contract-example/src/lib.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-macros/src/contract/methods.rs, crates/contracts/ab-system-contract-code/src/lib.rs, crates/contracts/ab-system-contract-state/Cargo.toml, crates/contracts/ab-system-contract-state/src/lib.rs, website/book/src/Execution_environment/Contracts_overview.md
This upgrades infrastructure in a few ways:
* API to read contract's code
* prefix for extension trait methods to prevent confusion
* `ab-system-contract-state` that is similar to `ab-system-contract-code` and manages state of other contracts (contracts overview in the book is updated to reflect this)
=> Infra updates

crates/contracts/ab-contracts-macros-impl/src/contract.rs
It is a better experience this way
=> Detect `#[update]` and `#[view]` methods with default implementation and disallow them

crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-macros-impl/src/contract.rs, crates/contracts/ab-contracts-macros/src/__private.rs
This will be helpful for running contracts where they need to be distinguished from each other
=> Introduce `Contract` trait

crates/contracts/ab-contracts-common/src/metadata/decode.rs
As follow-up to https://github.com/nazar-pc/abundance/pull/43 this allows to decode contract, trait and full (contract and trait metadata concatenated) decoding, not just decoding of method metadata
=> Full metadata decoding

crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-io-type/src/lib.rs, crates/contracts/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/ab-contracts-io-type/src/trivial_type.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-macros-impl/src/contract/method.rs
This places size and capacity as pointers next to the data pointer in both `InternalArgs` and `ExternalArgs` for easier processing by the host. Specifically this allows to read and write data structures sequentially in a single pass and for native executor simply map I/O pointers directly to each other rather than copying them manually after FFI call.
Refactoring before last commit is done to simplify things in the last commit and make ^ change possible.
=> FFI refactoring

crates/contracts/ab-contracts-common/src/metadata.rs, crates/contracts/ab-contracts-common/src/metadata/compact.rs, crates/contracts/ab-contracts-common/src/metadata/decode.rs, crates/contracts/ab-contracts-executor/src/lib.rs, crates/contracts/ab-contracts-io-type/src/metadata/tests.rs, crates/contracts/ab-contracts-macros-impl/src/contract/method.rs
This not only simplifies code, it also provides more flexibility to implementers since adding or removing slot address argument doesn't impact metadata anymore
=> Simplify slots FFI

Cargo.lock, crates/contracts/ab-contracts-executor/Cargo.toml, crates/contracts/ab-contracts-executor/src/aligned_buffer.rs, crates/contracts/ab-contracts-executor/src/aligned_buffer/tests.rs, crates/contracts/ab-contracts-executor/src/lib.rs, crates/contracts/ab-contracts-executor/src/slots.rs, crates/contracts/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/ab-contracts-macros/src/lib.rs
`Bytes` and `BytesMut` do not guarantee necessary alignment. Since we don't need dynamic resizing or other complex features, it is possible to implement a simpler version with alignment guarantees and better domain-specific API.
=> Replace bytes

Cargo.lock, crates/contracts/ab-contract-example-flipper/Cargo.toml, crates/contracts/ab-contract-example-flipper/src/lib.rs, crates/contracts/ab-contract-example-flipper/tests/basic.rs, crates/contracts/ab-contract-example-ft/Cargo.toml, crates/contracts/ab-contract-example-ft/src/lib.rs, crates/contracts/ab-contract-example-ft/tests/basic.rs, crates/contracts/ab-contract-playground/Cargo.toml, crates/contracts/ab-contract-playground/src/lib.rs, crates/contracts/ab-contract-playground/tests/basic.rs, crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-common/src/metadata.rs, crates/contracts/ab-contracts-common/src/metadata/compact.rs, crates/contracts/ab-contracts-common/src/metadata/decode.rs, crates/contracts/ab-contracts-executor/src/context.rs, crates/contracts/ab-contracts-executor/src/lib.rs, crates/contracts/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/ab-contracts-io-type/src/metadata/tests.rs, crates/contracts/ab-contracts-io-type/src/trivial_type.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-macros-impl/src/contract.rs, crates/contracts/ab-contracts-macros-impl/src/contract/method.rs, crates/contracts/ab-contracts-macros/Cargo.toml, crates/contracts/ab-contracts-macros/src/__private.rs, crates/contracts/ab-contracts-standards/Cargo.toml, crates/contracts/ab-system-contract-address-allocator/Cargo.toml, crates/contracts/ab-system-contract-code/Cargo.toml, crates/contracts/ab-system-contract-code/src/lib.rs, crates/contracts/ab-system-contract-state/Cargo.toml
This adds more examples of simpler contracts, including a trivial "flipper" contract (inspired by [ink!](https://use.ink/basics/contract-template/)).
There are also several API improvements that remove the need to use awkward and/or verbose syntax in integration tests.
And I also found some small bugs that were fixed too.
=> More examples

Cargo.lock, crates/contracts/ab-contract-example-flipper/Cargo.toml, crates/contracts/ab-contract-example-flipper/tests/basic.rs, crates/contracts/ab-contract-example-ft/Cargo.toml, crates/contracts/ab-contract-example-ft/tests/basic.rs, crates/contracts/ab-contract-playground/Cargo.toml, crates/contracts/ab-contract-playground/tests/basic.rs, crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-executor/Cargo.toml, crates/contracts/ab-contracts-executor/src/aligned_buffer.rs, crates/contracts/ab-contracts-executor/src/aligned_buffer/tests.rs, crates/contracts/ab-contracts-executor/src/context.rs, crates/contracts/ab-contracts-executor/src/context/ffi_call.rs, crates/contracts/ab-contracts-executor/src/lib.rs, crates/contracts/ab-contracts-executor/src/slots.rs, crates/contracts/ab-contracts-macros/src/lib.rs
This is a big rewrite of how slots are processed.
The key changes:
* tracking of changes across recursive method calls and catching conflicts correctly
* calling many methods at once is only allowed for `#[view]` method (efficiency constraint, see below)
* deterministic outcomes regardless of whether many methods are processed sequentially or in parallel
* more efficient data structures with some inline values for all key internals of `Slots`
I've attempted this probably more than 5 times, hitting complexity or efficiency roadblocks.
One of the features I wanted to have, but ultimately didn't find a way to achieve was recovering from slot access errors by method caller. This implies cloning (additional allocations) of several data structures that might be modified by the called method. …
=> Slots refactoring (more like rewrite)

crates/contracts/ab-contracts-executor/src/aligned_buffer.rs, crates/contracts/ab-contracts-executor/src/context/ffi_call.rs, crates/contracts/ab-contracts-executor/src/slots.rs
This ensures `#[init]` returns non-empty state, stateful methods are only called after successful `#[init]` and adds a bit more logging for debugging purposes
=> Follow up slots fixes

crates/contracts/ab-contract-example-ft/src/lib.rs, crates/contracts/ab-contract-playground/src/lib.rs, crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-executor/src/context.rs, crates/contracts/ab-contracts-executor/src/context/ffi_call.rs, crates/contracts/ab-contracts-executor/src/lib.rs, crates/contracts/ab-contracts-executor/src/slots.rs, crates/contracts/ab-system-contract-address-allocator/src/lib.rs
This increases address size to `u128` and keeps it as a number. While number requires larger alignment, it also generates much more compact RISC-V code. Also fixed address allocation.
With larger address type code became less efficient, so `Slots` was refactored to not use maps at all (given small expected number of slots used per transaction), which reduced memory usage and improved performance to almost the level it was prior.
=> Larger address and fix slots

crates/contracts/ab-contracts-executor/src/aligned_buffer.rs, crates/contracts/ab-contracts-executor/src/aligned_buffer/tests.rs, crates/contracts/ab-contracts-executor/src/context.rs, crates/contracts/ab-contracts-executor/src/slots.rs
This allows to increase number of flips from ~4M/s to ~5M/s!
The primary reason is extracting the most common special case with a single method call into a separate method that doesn't need to deal with iteration and heap allocation for method call.
`#[inline]` on private methods does nothing.
=> Optimize native execution context, remove useless `#[inline]`

crates/contracts/ab-contracts-common/Cargo.toml, crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-executor/Cargo.toml, crates/contracts/ab-contracts-macros-impl/src/contract.rs, crates/contracts/ab-contracts-macros-impl/src/contract/method.rs, crates/contracts/ab-contracts-macros/Cargo.toml, crates/contracts/ab-contracts-macros/src/__private.rs
With minor changes to executor (switching from `std` to `alloc`/`core`) this makes it possible to run contracts inside of contracts.
`alloc` feature will also be used for other things soon.
=> Add `executor` and `alloc` features to `ab-contracts-common` crate

crates/contracts/ab-contracts-executor/src/aligned_buffer.rs, crates/contracts/ab-contracts-executor/src/context.rs, crates/contracts/ab-contracts-executor/src/slots.rs, crates/contracts/ab-contracts-macros/src/lib.rs
Slot changes must not be persisted if call fails.
Also potential changes of `#[output]` and `#[result]` are documented. explicitly.
=> Revert slot modifications on failed call

Cargo.lock, crates/contracts/ab-contract-example-wallet/Cargo.toml, crates/contracts/ab-contract-example-wallet/src/lib.rs, crates/contracts/ab-contracts-common/Cargo.toml, crates/contracts/ab-contracts-common/src/address.rs, crates/contracts/ab-contracts-common/src/balance.rs, crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-common/src/method.rs, crates/contracts/ab-contracts-executor/Cargo.toml, crates/contracts/ab-contracts-executor/src/lib.rs, crates/contracts/ab-contracts-io-type/src/lib.rs, crates/contracts/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/ab-contracts-io-type/src/metadata.rs, crates/contracts/ab-contracts-io-type/src/metadata/type_details.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-io-type/src/variable_elements.rs, crates/contracts/ab-contracts-macros-impl/src/contract.rs, crates/contracts/ab-contracts-macros-impl/src/contract/method.rs, crates/contracts/ab-contracts-standards/Cargo.toml, crates/contracts/ab-contracts-standards/src/lib.rs, crates/contracts/ab-contracts-standards/src/tx_handler.rs, crates/contracts/ab-contracts-trivial-type-derive/src/lib.rs, crates/contracts/ab-system-contract-simple-wallet-base/Cargo.toml, crates/contracts/ab-system-contract-simple-wallet-base/src/lib.rs, crates/contracts/ab-system-contract-simple-wallet-base/src/payload.rs, crates/contracts/ab-system-contract-simple-wallet-base/src/payload/builder.rs, crates/contracts/ab-system-contract-state/src/lib.rs
This introduces `TxHandler` trait in `ab-contracts-standards` that will be used by the execution environment to process transactions. The interface is super generic to not make too many assumptions about what transactions look like. This allows to make wallets as simple or as complex as necessary. It also facilitates zero-copy APIs and doesn't require heap allocations.
The execution environment itself will be made aware of this interface in the future with a separate PR.
To demonstrate what the wallet might potentially look like two new crates were added.
`ab-system-contract-simple-wallet-base` includes modules for serializing/deserializing method calls to/from payload as well as a contract that uses SR25519 signature scheme to facilitate implementation of `TxHandler`. It is not a wallet …
=> Transaction interface and simple wallet implementation

Cargo.lock, crates/contracts/ab-contract-example-wallet/src/lib.rs, crates/contracts/ab-contracts-io-type/src/trivial_type.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-io-type/src/variable_elements.rs, crates/contracts/ab-system-contract-simple-wallet-base/Cargo.toml, crates/contracts/ab-system-contract-simple-wallet-base/src/lib.rs
Reading of the state internally was not flexible enough for some use cases like when a wallet might have several nonces/keypairs stored in its state.
Also a few utility methods introduced on `VariableBytes` and `VariableElements` that make it easier to compose larger apps with safe APIs.
=> Improve `ab-system-contract-simple-wallet-base` API

crates/contracts/ab-contract-playground/src/lib.rs, crates/contracts/ab-contract-playground/tests/basic.rs, crates/contracts/ab-contracts-common/src/metadata.rs, crates/contracts/ab-contracts-common/src/metadata/compact.rs, crates/contracts/ab-contracts-common/src/metadata/decode.rs, crates/contracts/ab-contracts-common/src/metadata/tests.rs, crates/contracts/ab-contracts-executor/src/context/ffi_call.rs, crates/contracts/ab-contracts-macros-impl/src/contract/init.rs, crates/contracts/ab-contracts-macros-impl/src/contract/method.rs, crates/contracts/ab-contracts-macros-impl/src/contract/update.rs, crates/contracts/ab-contracts-macros-impl/src/contract/view.rs, crates/contracts/ab-contracts-macros-impl/src/lib.rs, crates/contracts/ab-contracts-macros/src/lib.rs, crates/contracts/ab-system-contract-simple-wallet-base/src/lib.rs, crates/contracts/ab-system-contract-simple-wallet-base/src/payload.rs, crates/contracts/ab-system-contract-simple-wallet-base/src/payload/builder.rs
This finally replaces `#[result]` with `#[output]` and unifies a few things, while also removing a bunch of code.
It is a bit tricky that last `#[output]` can now be used an an alternative for result, but hopefully that is not too confusing. If it is, that behavior can be removed, forcing developers to use `#[update]` instead of `#[init]` and calling state contract directly.
=> Remove `#[result]`

crates/contracts/ab-contracts-common/src/error.rs
It may happen on upgrade/mismatch of components and must be handled more gracefully than a crash
=> Replace `unreachable!()` in `ContractError` handling

crates/contracts/ab-contract-example-wallet/benches/flip.rs, crates/contracts/ab-contract-example-wallet/tests/flip.rs, crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-executor/src/lib.rs, crates/contracts/ab-contracts-test-utils/src/transaction_builder.rs
I expect `Transaction` to be much more popular in APIs, but its contents will come from various sources (like network stack, RPC, etc.) and in all of those cases allocation avoidance will be desirable
=> Refactor transaction types

crates/contracts/ab-contracts-executor/src/context.rs, crates/contracts/ab-contracts-executor/src/lib.rs, crates/contracts/ab-contracts-executor/src/slots.rs
It'll become more effective once there is less heap allocation in slots, but provides a minor performance improvement for execution already
=> Special case read-only slots instance

crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-io-type/src/variable_elements.rs, crates/contracts/ab-contracts-standards/src/tx_handler.rs, crates/contracts/ab-system-contract-simple-wallet-base/src/lib.rs
This makes thing a bit more readable in a simple case
=> Allow to not specify `0` explicitly in `VariableBytes` and `VariableElements`

crates/contracts/system/ab-system-contract-simple-wallet-base/src/lib.rs
This would have been fine in the contract of end user, but potential memory corruption from user input is problematic for system contract
=> Do not use unchecked payload parsing

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, crates/contracts/system/ab-system-contract-simple-wallet-base/Cargo.toml, crates/contracts/system/ab-system-contract-simple-wallet-base/src/lib.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload/builder/tests.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/seal.rs
A bit more verbose, but allows to statically guarantee there will be no panics no matter the input. Also reduced the number of mathematical operations that do not have any underflow/overflow checks.
This is just for one crate, more crates will follow. Corresponding CI workflow added too.
=> Initial support for `no-panic` in `ab-syse-contract-simple-wallet-base`

.github/workflows/rust.yml, crates/contracts/core/ab-contracts-common/Cargo.toml, crates/contracts/core/ab-contracts-common/src/address.rs, crates/contracts/core/ab-contracts-common/src/balance.rs, crates/contracts/core/ab-contracts-common/src/env.rs, crates/contracts/core/ab-contracts-common/src/error.rs, crates/contracts/core/ab-contracts-common/src/lib.rs, crates/contracts/core/ab-contracts-common/src/metadata.rs, crates/contracts/core/ab-contracts-common/src/method.rs, crates/contracts/core/ab-contracts-executor/src/context.rs, crates/contracts/core/ab-contracts-executor/src/context/ffi_call.rs, crates/contracts/core/ab-contracts-executor/src/lib.rs, crates/contracts/core/ab-contracts-test-utils/Cargo.toml
It'd be nice for the contract to be able to host other contracts, but the fact that there is a single `Env` struct causes difficulties. I think `HostEnv` and `GuestEnv`/`Env` separation is needed, possibly with `EnvLike` trait that will be implemented for both and might be useful elsewhere.
But all that will be later, for now this should be fine and already provides a nice performance improvement, especially for transaction emulation, which is much closer to the direct execution now (which also got a tiny bit faster):
```
flipper/direct          time:   [75.096 ns 75.394 ns 75.737 ns]
thrpt:  [13.204 Melem/s 13.264 Melem/s 13.316 Melem/s]
flipper/transaction     time:   [79.468 ns 79.776 ns 80.143 ns]
thrpt:  [12.478 Melem/s 12.535 Melem/s 12.584 Melem/s]
```
=> Remove the need for `alloc` in `Env` by taking a reference to the executor context

crates/contracts/core/ab-contracts-executor/src/aligned_buffer.rs, crates/contracts/core/ab-contracts-executor/src/aligned_buffer/tests.rs, crates/contracts/core/ab-contracts-executor/src/lib.rs, crates/contracts/core/ab-contracts-test-utils/src/lib.rs
This replaced `Arc` with a more efficient and internally simpler implementation, also `LazyLock` usage was replaced with a static unconditionally available instance.
As the result performance improved even further:
```
flipper/direct          time:   [68.005 ns 68.284 ns 68.600 ns]
thrpt:  [14.577 Melem/s 14.645 Melem/s 14.705 Melem/s]
flipper/transaction     time:   [71.065 ns 71.352 ns 71.711 ns]
thrpt:  [13.945 Melem/s 14.015 Melem/s 14.072 Melem/s]
time:   [3.0973 µs 3.1050 µs 3.1141 µs]
thrpt:  [321.12 Kelem/s 322.07 Kelem/s 322.86 Kelem/s]
```
The only thing preventing `NativeExecutor` from being usable in `no_std` environment with `alloc` is `HashMap` usage, which can be replaced with `BTreeMap`, but will be slower. Once there is a need for that, a new …
=> Faster `AlignedBuffer`

crates/contracts/core/ab-contracts-executor/src/aligned_buffer.rs, crates/contracts/core/ab-contracts-executor/src/context/ffi_call.rs
This is probably the last optimization there for now:
```
flipper/direct          time:   [66.476 ns 66.701 ns 66.967 ns]
thrpt:  [14.933 Melem/s 14.992 Melem/s 15.043 Melem/s]
flipper/transaction     time:   [70.278 ns 70.571 ns 70.911 ns]
thrpt:  [14.102 Melem/s 14.170 Melem/s 14.229 Melem/s]
```
=> Refacor `AlignedBuffer`

.github/workflows/rust.yml, Cargo.lock, crates/contracts/core/ab-contracts-common/Cargo.toml, crates/contracts/core/ab-contracts-common/src/address.rs, crates/contracts/core/ab-contracts-common/src/balance.rs, crates/contracts/core/ab-contracts-common/src/env.rs, crates/contracts/core/ab-contracts-common/src/error.rs, crates/contracts/core/ab-contracts-common/src/metadata/compact.rs, crates/contracts/core/ab-contracts-common/src/metadata/decode.rs, crates/contracts/core/ab-contracts-io-type/src/metadata.rs, crates/contracts/core/ab-contracts-io-type/src/metadata/type_name.rs, crates/contracts/system/ab-system-contract-state/src/lib.rs
UTF-8 parsing had to go because it prevented compiler from proving that panic can't happen, it also was non-negligible amount of compute, which resulted in a substantial speed-up:
```
flipper/direct          time:   [61.179 ns 61.433 ns 61.735 ns]
thrpt:  [16.198 Melem/s 16.278 Melem/s 16.345 Melem/s]
flipper/transaction     time:   [64.810 ns 65.026 ns 65.281 ns]
thrpt:  [15.318 Melem/s 15.378 Melem/s 15.430 Melem/s]
time:   [3.0185 µs 3.0249 µs 3.0321 µs]
thrpt:  [329.81 Kelem/s 330.59 Kelem/s 331.29 Kelem/s]
```
Also tweaked inlining attributes, removing `always` from some of them and adding `#[inline]` to others to help compiler prove where panics can't happen.
`const fn` methods are not supported yet (can't have `Drop` trait in const), so those are …
=> Make a bunch of methods in `ab-contracts-common` `no-panic`, remove UTF-8 parsing

crates/contracts/core/ab-contract-playground/src/lib.rs, crates/contracts/core/ab-contract-playground/tests/basic.rs, crates/contracts/core/ab-contracts-executor/src/context.rs, crates/contracts/core/ab-contracts-executor/src/context/ffi_call.rs, crates/contracts/core/ab-contracts-executor/src/lib.rs, crates/contracts/core/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/core/ab-contracts-slots/src/slots.rs, crates/contracts/core/ab-contracts-trivial-type-derive/src/lib.rs
Now `#[tmp]` is actually ephemeral and automatically cleaned up after transaction processing
=> `#[tmp]` automatic cleanup

crates/contracts/core/ab-contracts-common/src/env.rs, crates/contracts/core/ab-contracts-common/src/lib.rs, crates/contracts/core/ab-contracts-common/src/metadata.rs, crates/contracts/core/ab-contracts-executor/src/context/ffi_call.rs, crates/contracts/core/ab-contracts-macros-impl/src/contract/method.rs, crates/contracts/core/ab-contracts-macros/src/__private.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/lib.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload/builder.rs
This makes transaction execution A LOT faster:
```
time:   [611.07 ns 613.71 ns 616.75 ns]
thrpt:  [1.6214 Melem/s 1.6294 Melem/s 1.6365 Melem/s]
```
Explicit limit for number of arguments will be leveraged to further improve performance and to allow easier and more compact implementation of more advanced transaction payload encoding (with ability to reference outputs for slots, not just inputs).
=> Faster transaction processing

.github/workflows/rust.yml, crates/contracts/core/ab-contracts-common/src/env.rs, crates/contracts/core/ab-contracts-common/src/lib.rs, crates/contracts/core/ab-contracts-common/src/transaction.rs, crates/contracts/core/ab-contracts-executor/src/lib.rs, crates/contracts/core/ab-contracts-io-type/src/metadata.rs, crates/contracts/core/ab-contracts-standards/src/tx_handler.rs, crates/contracts/core/ab-contracts-test-utils/src/dummy_wallet.rs, crates/contracts/core/ab-contracts-test-utils/src/transaction_builder.rs, crates/contracts/example/ab-example-contract-wallet/benches/example-contract-wallet.rs, crates/contracts/example/ab-example-contract-wallet/src/lib.rs, crates/contracts/example/ab-example-contract-wallet/tests/flip.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/lib.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload/builder.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload/builder/tests.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/seal.rs
The biggest change here is transaction payload encoding/decoding rewrite. Not only it now supports using outputs of previous method calls for slots (only inputs were supported before), it also builds payload incrementally. Incremental building means it will be possible to make it work in `no_std` environment with little effort if needed, which might be useful.
There were also a few bugs in not yet tested code paths that were fixed, for example outputs have optional `TypeDetails` (for `#[init]`'s last `#[output]`), but encoding wasn't aware of this distinction, resulting in invalid encoding in some cases.
And lastly, the encoding of transactions should generally be more compact than before due to better alignment.
=> Transaction refactoring

crates/contracts/core/ab-contracts-executor/src/context/ffi_call.rs
This further improves performance:
```
flipper/direct          time:   [48.326 ns 48.469 ns 48.638 ns]
thrpt:  [20.560 Melem/s 20.632 Melem/s 20.693 Melem/s]
flipper/transaction     time:   [57.682 ns 57.933 ns 58.219 ns]
thrpt:  [17.177 Melem/s 17.261 Melem/s 17.336 Melem/s]
time:   [535.60 ns 537.22 ns 539.44 ns]
thrpt:  [1.8538 Melem/s 1.8614 Melem/s 1.8671 Melem/s]
```
=> Improve `make_ffi_call` performance (part 2)

Cargo.toml, crates/contracts/core/ab-contracts-macros-impl/src/contract.rs, crates/contracts/core/ab-contracts-macros/src/lib.rs
Once I figure out what target it'll be compiled to, will add corresponding tests
=> Add various tweaks needed for `no_std` contracts without OS

.github/workflows/rust.yml, crates/contracts/x86_64-unknown-none-abundance.json
This splits Miri into a separate job for better concurrency and add `contracts` job that builds contracts for a custom `no_std` target
=> CI updates

subspace/crates/pallet-subspace/src/lib.rs, subspace/crates/pallet-subspace/src/mock.rs, subspace/crates/pallet-subspace/src/tests.rs, subspace/crates/subspace-core-primitives/src/pot.rs, subspace/crates/subspace-node/src/chain_spec.rs, subspace/crates/subspace-runtime/src/lib.rs
This refactors constants (removes from `pallet-subspace` those that are not used there) and cleans up a bunch of stuff that is no longer relevant in reduced implementation.
This should make it easier to extract things out of the pallet later.
@adlrocha FYI
=> Subspace refactoring and cleanup

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, crates/contracts/system/ab-system-contract-simple-wallet-base/Cargo.toml, crates/shared/ab-merkle-tree/Cargo.toml, crates/shared/ab-merkle-tree/src/balanced_hashed.rs, crates/shared/ab-merkle-tree/src/lib.rs, crates/shared/ab-merkle-tree/tests/balanced_hashed.rs
This introduces `ab-merkle-tree` crate with `BalancedHashedMerkleTree` Merkle Tree implementation. It is narrowly scoped and I expect either another implementation to be introduced that handles cases with trees that are unbalanced and/or have arbitrary leaf size.
Ultimately we want to replace this with a native tree of blake3 hash, such that the root is the same as if we just hashed the leafs with blake3 directly, but that will take more effort and this should already be sufficient to swap KZG in the archiver.
=> Add `ab-merkle-tree` crate

specs/subspace-diff.md, subspace/Cargo.lock, subspace/crates/subspace-archiving/src/archiver.rs, subspace/crates/subspace-archiving/src/piece_reconstructor.rs, subspace/crates/subspace-archiving/tests/integration/archiver.rs, subspace/crates/subspace-core-primitives/src/pieces.rs, subspace/crates/subspace-farmer-components/Cargo.toml, subspace/crates/subspace-farmer-components/src/plotting.rs, subspace/crates/subspace-farmer-components/src/proving.rs, subspace/crates/subspace-farmer-components/src/reading.rs, subspace/crates/subspace-farmer-components/src/sector.rs, subspace/crates/subspace-farmer/src/bin/subspace-farmer/commands/cluster/controller.rs, subspace/crates/subspace-farmer/src/bin/subspace-farmer/commands/farm.rs, subspace/crates/subspace-farmer/src/farmer_piece_getter/piece_validator.rs, subspace/crates/subspace-service/src/lib.rs, subspace/crates/subspace-service/src/sync_from_dsn/piece_validator.rs, subspace/crates/subspace-verification/Cargo.toml, subspace/crates/subspace-verification/src/lib.rs
This changes the way record chunks are committed to and includes parity chunks root in the piece (see spec update).
There is some awkwardness in solution proving/verification due to erasure coding library producing interleaved chunks and record commitment in archiver assuming all source chunks go before parity chunks. This is because erasure coding library will be swapped later with a different and faster alternative, which will not do interleaving anymore (at least I expect it will not).
Not doing interleaving is a huge help with data retrieval too (as learned in Subspace). It is tricky enough to retrieve data as is with parts of it potentially crossing segment boundary. Interleaving data within a segment causes even more complexity with extra helper functions that I'd rather not have. …
=> Refactor record commitment

subspace/Cargo.lock, subspace/Cargo.toml, subspace/crates/sp-consensus-subspace/Cargo.toml, subspace/crates/subspace-archiving/Cargo.toml, subspace/crates/subspace-archiving/src/archiver.rs, subspace/crates/subspace-archiving/src/lib.rs, subspace/crates/subspace-archiving/src/piece_reconstructor.rs, subspace/crates/subspace-archiving/src/reconstructor.rs, subspace/crates/subspace-core-primitives/src/lib.rs, subspace/crates/subspace-erasure-coding/Cargo.toml, subspace/crates/subspace-erasure-coding/src/lib.rs, subspace/crates/subspace-erasure-coding/src/tests.rs, subspace/crates/subspace-farmer-components/Cargo.toml, subspace/crates/subspace-farmer-components/src/lib.rs, subspace/crates/subspace-farmer-components/src/plotting.rs, subspace/crates/subspace-farmer-components/src/proving.rs, subspace/crates/subspace-farmer-components/src/reading.rs, subspace/crates/subspace-verification/Cargo.toml, subspace/crates/subspace-verification/src/lib.rs
This replaces KZG-based erasure coding with much faster `reed-solomon-simd`.
The rest of the architecture is still the same: 31-byte raw record chunks, interleaved source and parity chunks/pieces. A lot of TODOs were added to change that.
I have not adjusted tests in `subspace-erasure-coding` yet, but it is being tested indirectly by `subspace-archiving` crate. The reason is that I want to improve API before writing tests, it is currently unnecessarily annoying to use and will get better as interleaving is removed and all chunks are 32 bytes.
Archiving performance improved as well from ~2.13 seconds to 0.5s, with plenty optimizations left to be done.
Block production, of course, still works.
=> Replace erasure coding library

.github/workflows/rust.yml
Networking on Windows to GitHub's servers is so bad, it is faster not to use cache. That is when it doesn't fail altogether.
Disable caching on Windows to speed things up.
=> Disable cache on Windows

crates/shared/ab-merkle-tree/src/balanced_hashed.rs, crates/shared/ab-merkle-tree/src/lib.rs, crates/shared/ab-merkle-tree/tests/balanced_hashed.rs, subspace/crates/pallet-subspace/Cargo.toml, subspace/crates/sp-consensus-subspace/Cargo.toml, subspace/crates/subspace-archiving/Cargo.toml, subspace/crates/subspace-archiving/src/archiver.rs, subspace/crates/subspace-archiving/src/piece_reconstructor.rs, subspace/crates/subspace-farmer-components/src/proving.rs, subspace/crates/subspace-farmer/Cargo.toml, subspace/crates/subspace-verification/Cargo.toml, subspace/crates/subspace-verification/src/lib.rs
This makes API more convenient, avoids allocations in many cases and enables full API of `subspace-verification` without the need of a global allocator.
This also improves archiving performance further. While the benchmark is flaky, I saw the time as low as 0.24s and even single core archiving is now twice as fast a multi-core previously at 1.8s.
There are still more optimizations to do, but this is quite decent as is.
=> Faster Merkle Tree Root creation

crates/contracts/core/ab-contracts-io-type/src/bool.rs, crates/contracts/core/ab-contracts-io-type/src/fixed_capacity_bytes.rs, crates/contracts/core/ab-contracts-io-type/src/fixed_capacity_string.rs, crates/contracts/core/ab-contracts-io-type/src/lib.rs, crates/contracts/core/ab-contracts-io-type/src/metadata.rs, crates/contracts/core/ab-contracts-io-type/src/metadata/compact.rs, crates/contracts/core/ab-contracts-io-type/src/metadata/tests.rs, crates/contracts/core/ab-contracts-io-type/src/metadata/type_details.rs, crates/contracts/core/ab-contracts-io-type/src/metadata/type_name.rs, crates/contracts/core/ab-contracts-io-type/src/trivial_type.rs, crates/contracts/example/ab-example-contract-flipper/benches/flip.rs, crates/contracts/example/ab-example-contract-flipper/src/lib.rs, crates/contracts/example/ab-example-contract-flipper/tests/basic.rs, crates/contracts/example/ab-example-contract-wallet/benches/example-contract-wallet.rs, crates/contracts/example/ab-example-contract-wallet/tests/flip.rs, crates/contracts/system/ab-system-contract-state/src/lib.rs
`Bool` is an alternative for `bool` that is UB-safe for any bit pattern.
`FixedCapacityBytesU8` and `FixedCapacityBytesU16` are fixed size containers implementing `TrivialType`, which are helpful for composition when it is necessary to allow for differently sized inputs as fields in a struct, but undesirable to deal with `VariableBytes` that erases inner type information.
`FixedCapacityStringU8` and `FixedCapacityStringU16` are similarly to bytes and are in fact just wrappers, but semantically are storing UTF-8 bytes, which is useful for presenting their contents in UI as text instead of hex bytes.
This allows to do things like this:
```rust
#[derive(Copy, Clone, TrivialType)]
#[repr(C)]
struct Item {
title: FixedCapacityStringU8<255>,
description: FixedCapacityStringU16<1024>,
}
```
In …
=> More trivial types

crates/contracts/core/ab-contracts-macros-impl/src/contract.rs, crates/contracts/core/ab-contracts-macros-impl/src/contract/method.rs
This may help with IDE support if IDE is smart enough (IntelliJ Rust plugin isn't)
=> Add more spans to macro-generated code

crates/contracts/core/ab-contracts-test-utils/src/transaction_builder.rs, crates/contracts/example/ab-example-contract-wallet/benches/example-contract-wallet.rs, crates/contracts/example/ab-example-contract-wallet/tests/basic.rs, crates/execution/ab-executor-native/src/lib.rs, crates/shared/ab-core-primitives/src/lib.rs, crates/shared/ab-core-primitives/src/transaction.rs, crates/shared/ab-core-primitives/src/transaction/owned.rs
This reduces wasted space from 12 bytes to 4 and version might in fact be useful in the future
=> Add a version to transaction header to reduce wasted space in owned transaction

specs/discussions/parking-lot.md
This PR adds _the parking lot_, where I am starting to collect all the discussions that we've been having sync or a sync of things that need to be defined further in the future but that we've "parked" until we have designed more core components that we could build upon. I didn't want all this to be lost on my meeting notes so I decided to start sharing them publicly.
=> spec discussions parking lot

Cargo.lock, Cargo.toml, crates/contracts/system/ab-system-contract-address-allocator/src/lib.rs, crates/execution/ab-executor-native/src/context.rs, crates/execution/ab-executor-slots/src/lib.rs, crates/shared/ab-core-primitives/Cargo.toml, crates/shared/ab-core-primitives/src/address.rs, crates/shared/ab-core-primitives/src/shard.rs, crates/shared/ab-core-primitives/tests/address.rs, subspace/Cargo.lock
This implements address formatting.
The format is based on Bech32m from [BIP-350](https://github.com/bitcoin/bips/blob/60ac0e8feccb07f891fd984e4ed76105d2898609/bip-0350.mediawiki) with better readability thanks to built-in separators and more compact representation in many cases.
The first step is to treat `u128` inside `Address` as big-endian sequence of bytes that will be encoded with Bech32m. First 20 bits correspond to shard index, the remaining 108 bits are allocated addresses within that shard.
The first step is to simply encode an address with Bech32m, for `Address::NULL` it'll look like this:
```
abc1qqqqqqqqqqqqqqqqqqqqqqqqqqldnky6
```
Next step is to visually separate the address into sections. The first 4 characters after `1` correspond to shard index (each character encodes 5 …
=> Address formatting

crates/shared/ab-core-primitives/src/block.rs, crates/shared/ab-core-primitives/src/block/body.rs, crates/shared/ab-core-primitives/src/block/header.rs, crates/shared/ab-core-primitives/src/lib.rs, crates/shared/ab-core-primitives/src/pot.rs, crates/shared/ab-core-primitives/src/segments.rs, crates/shared/ab-core-primitives/src/shard.rs, crates/shared/ab-core-primitives/src/solutions.rs, crates/shared/ab-core-primitives/src/transaction.rs, crates/shared/ab-core-primitives/src/transaction/owned.rs, crates/shared/ab-core-primitives/src/transaction/owned/builder_buffer.rs, crates/shared/ab-merkle-tree/src/balanced_hashed.rs, crates/shared/ab-merkle-tree/src/lib.rs, subspace/crates/pallet-subspace/src/mock.rs, subspace/crates/subspace-farmer-components/src/proving.rs
First few commits are preparation, the last one implements `Block`, `BlockHeader` and `BlockBody` that to the best of my knowledge right now, implement most of the things needed for hierarchical consensus.
Those data structures only provide the shape and ability to decode data structures from bytes. Builders and owned versions of the data structures will be added separately.
In general there are 4 flavors of each data structure:
* beacon chain
* intermediate shard
* leaf shard
* wrapper enum with 3 variants that correspond to above variants
Block header contains everything that might be needed by a light client for consensus verification. Block body contains PoT checkpoints, segment roots and child shards information alongside user transactions.
Information about child shards includes …
=> Block layout

crates/shared/ab-proof-of-time/src/aes.rs, crates/shared/ab-proof-of-time/src/aes/x86_64.rs, crates/shared/ab-proof-of-time/src/lib.rs
Another 2x performance improvement on Zen 4.
Before:
```
verify                  time:   [204.92 ms 205.10 ms 205.30 ms]
```
After:
```
verify                  time:   [102.38 ms 102.43 ms 102.53 ms]
```
On this particular CPU verification is 16x faster than proving, which matches expected dual AES units per CPU core with 0.5 clocks per instruction:
```
2 AES units * 4 blocks at a time / 0.5 CPI = 16
```
:muscle:
=> Faster PoT verification for CPUs that support AVX512F+VAES

crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/chiapos/table/tests.rs, crates/shared/ab-proof-of-space/src/chiapos/table/types.rs
Before:
```
chia/table/single       time:   [1.0668 s 1.0756 s 1.0862 s]
chia/table/parallel/8x  time:   [905.01 ms 919.11 ms 933.34 ms]
chia/verification       time:   [11.094 µs 11.533 µs 11.985 µs]
```
After:
```
chia/table/single       time:   [1.0245 s 1.0329 s 1.0432 s]
chia/table/parallel/8x  time:   [830.37 ms 843.37 ms 855.47 ms]
chia/verification       time:   [8.9454 µs 8.9612 µs 8.9726 µs]
```
Also less code and a bit easier to read.
I had some other tweaks locally, but at least until https://github.com/BLAKE3-team/BLAKE3/issues/478 is available it hurts more than helps.
=> Improve pos vectorization and pipelining

crates/shared/ab-proof-of-time/src/aes.rs, crates/shared/ab-proof-of-time/src/aes/x86_64.rs
There are CPUs with VAES that do not support AVX512F, which requires a special version of code to make it work with AVX2 and narrower registers
=> Implement PoT verification optimized for AVX2+VAES and AES+SSE4.1

.github/workflows/rust.yml, crates/shared/ab-proof-of-time/Cargo.toml, crates/shared/ab-proof-of-time/src/aes.rs, crates/shared/ab-proof-of-time/src/aes/aarch64.rs, crates/shared/ab-proof-of-time/src/aes/x86_64.rs, crates/shared/ab-proof-of-time/src/lib.rs, subspace/docker/bootstrap-node.Dockerfile, subspace/docker/farmer.Dockerfile, subspace/docker/node.Dockerfile, subspace/docker/runtime.Dockerfile
This implements optimized implementation of PoT proving and verification on aarch64.
Before (Raspberry PI 5):
```
verify                  time:   [1.1665 s 1.1817 s 1.1976 s]
```
After:
```
verify                  time:   [835.30 ms 835.30 ms 835.31 ms]
```
I'm not sure why runtime detection is so expensive in `aes` crate (https://github.com/RustCrypto/block-ciphers/issues/484), but we certainly avoid doing the check on each iteration by implementing an efficient implementation + saving some on extra XORs. When compiled with `RUSTFLAGS="-C target-feature=+aes"` `aes` crate improves, but not quite to the same level as optimized implementation, so this is a substantial win either way for generic aarch64 platforms (not sure about the impact on macOS, I think `+aes` is implied there by …
=> Implement PoT proving and verification optimized for AES (aarch64)

.github/workflows/rust.yml, crates/contracts/system/ab-system-contract-simple-wallet-base/src/lib.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload/builder.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/seal.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/utils.rs, crates/shared/ab-proof-of-time/src/aes.rs, crates/shared/ab-proof-of-time/src/aes/aarch64.rs, crates/shared/ab-proof-of-time/src/lib.rs
With updated `RUSTFLAGS` more code can be checked, but crucially heap allocations seem to block some of the usage (likely due to `Vec`) and it is not clear if it can be resolved since heap allocations are inherently fallible on hardware level and most often not handled at all on application level.
UPD: After countless attempts managed to enable Windows, extend various tests and even improve logging.
=> Extend `no-panic` usage in crates where it was used already, other CI improvements

crates/node/ab-client-api/src/lib.rs, crates/node/ab-client-proof-of-time/src/source.rs, crates/shared/ab-core-primitives/src/block.rs, crates/shared/ab-core-primitives/src/block/body.rs, crates/shared/ab-core-primitives/src/block/body/owned.rs, crates/shared/ab-core-primitives/src/block/header.rs, crates/shared/ab-core-primitives/src/block/header/owned.rs, crates/shared/ab-core-primitives/src/block/owned.rs, subspace/crates/sc-consensus-subspace-rpc/src/lib.rs, subspace/crates/sc-consensus-subspace/src/slot_worker.rs, subspace/crates/subspace-service/src/lib.rs, subspace/crates/subspace-service/src/rpc.rs
Extracted from local branch more block-related infrastructure, primarily introducing `Generic{,Owned}Block{,Header,Body}` traits that make it possible to reason about blocks in generic way. Some of it is quite painful to use due to the state of generics in Rust (even nightly), but it is a sufficient foundation for now.
=> Block infrastructure improvements

crates/shared/ab-core-primitives/src/block/body.rs, crates/shared/ab-core-primitives/src/block/body/owned.rs, crates/shared/ab-core-primitives/src/block/owned.rs
There will be no transactions on intermediate shards to reduce overhead for farmers
=> Remove intermediate shard transactions

crates/shared/ab-core-primitives/src/block/body.rs, crates/shared/ab-core-primitives/src/block/header.rs, crates/shared/ab-merkle-tree/src/balanced_hashed.rs, crates/shared/ab-merkle-tree/src/unbalanced_hashed.rs, crates/shared/ab-merkle-tree/tests/balanced_hashed.rs, crates/shared/ab-merkle-tree/tests/unbalanced_hashed.rs
I first noticed that unbalanced implementation could panic if `MAX_N` was specified incorrectly.
I then looked closer into `active_levels` and it became clear that it is just a number of leaves, so decided to simplify the implementation. Especially balanced implementation is very elegant now.
There are no dedicated Merkle Tree benchmarks yet, but archiving that uses it shows clear and non-negligible improvement.
```
Before:
segment-archiving-whole-segment
time:   [1.9043 s 1.9133 s 1.9230 s]
After:
segment-archiving-whole-segment
time:   [1.8101 s 1.8152 s 1.8202 s]
```
=> Improve Merkle Tree implementation

Cargo.lock, Cargo.toml, crates/shared/ab-core-primitives/Cargo.toml, crates/shared/ab-core-primitives/src/block/header.rs, crates/shared/ab-core-primitives/src/ed25519.rs, subspace/Cargo.lock, subspace/Cargo.toml, subspace/crates/sp-consensus-subspace/src/digests.rs, subspace/crates/subspace-verification/Cargo.toml
With https://github.com/ZcashFoundation/ed25519-zebra/pull/161 and https://github.com/ZcashFoundation/ed25519-zebra/pull/174 `alloc` is no longer needed. Using upstream `main` for now until they have a new release.
Also included some refactoring to seal check from local branch.
=> Enable ed25519 verification unconditionally

.github/workflows/gh-pages.yml, .github/workflows/rust.yml, Cargo.lock, Cargo.toml, crates/shared/ab-proof-of-space/Cargo.toml, crates/shared/ab-proof-of-space/src/chiapos/table.rs, subspace/.github/workflows/rust.yml, subspace/Cargo.lock
This also updates `aes` crate to a similar version
=> Update `chacha20` with API that writes keystream without XORing it

Cargo.lock, Cargo.toml, crates/farmer/ab-farmer-components/Cargo.toml, crates/node/ab-client-block-authoring/Cargo.toml, crates/node/ab-client-block-import/Cargo.toml, crates/node/ab-client-block-import/src/beacon_chain.rs, crates/node/ab-client-block-import/src/importing_blocks.rs, crates/node/ab-client-block-import/src/lib.rs, crates/node/ab-client-proof-of-time/Cargo.toml, crates/shared/ab-core-primitives/src/block/body/owned.rs, crates/shared/ab-core-primitives/src/block/header.rs, crates/shared/ab-core-primitives/src/block/header/owned.rs, crates/shared/ab-core-primitives/src/block/owned.rs, crates/shared/ab-core-primitives/src/lib.rs
This resolves some TODOs by buffering blocks that are being imported, allowing for import of all blocks in the sequence to happen concurrently.
There were also some fixes and tweaks in the first two commits.
=> Import blocks buffering

Cargo.lock, crates/farmer/ab-farmer-components/src/proving.rs, crates/node/ab-client-api/Cargo.toml, crates/node/ab-client-api/src/lib.rs, crates/node/ab-client-block-import/Cargo.toml, crates/node/ab-client-block-import/src/beacon_chain.rs, crates/node/ab-client-block-import/src/importing_blocks.rs, crates/node/ab-client-block-import/src/lib.rs, crates/node/ab-client-block-verification/src/beacon_chain.rs, crates/node/ab-client-block-verification/src/lib.rs, crates/shared/ab-core-primitives/src/block/body.rs, crates/shared/ab-core-primitives/src/block/body/owned.rs, crates/shared/ab-core-primitives/src/block/header/owned.rs, crates/shared/ab-core-primitives/src/solutions.rs, crates/shared/ab-merkle-tree/src/mmr.rs, crates/shared/ab-merkle-tree/tests/balanced.rs, crates/shared/ab-merkle-tree/tests/unbalanced.rs, subspace/Cargo.lock
There are a few commits with various tweaks and preparation, while last commit implements block MMR maintenance and verification.
Persistence abstraction trait was added to persist both block and its MMR. It'll need to be extended with more arguments (something related to state at least) later.
=> Block MMR verification

.github/workflows/rust.yml
There will be a lot more jobs created now, but thanks to `rust-all` aggregated job it should be easier to handle and it does result in lower overall CI times, which should also scale a bit better as more code is written.
=> Higher CI concurrency

crates/shared/ab-core-primitives/Cargo.toml, crates/shared/ab-core-primitives/src/lib.rs
This should have been a part of https://github.com/nazar-pc/abundance/pull/308, but GitHub merged it for some reason despite failing status checks :confused:
=> Switch to `rclite::Arc` for smaller size and better performance in low-level crates

.github/workflows/rust.yml
`rust-all` might be skipped one of the checks it depends on have failed, which results in PR being merged instead of blocked. This introduces counter-intuitive workaround for such case.
=> Fix CI checks

Cargo.lock, crates/shared/ab-blake3/Cargo.toml, crates/shared/ab-blake3/src/const_fn.rs, crates/shared/ab-blake3/src/const_fn/hazmat.rs, crates/shared/ab-blake3/src/const_fn/hazmat/tests.rs, crates/shared/ab-blake3/src/const_fn/platform.rs, crates/shared/ab-blake3/src/const_fn/portable.rs, crates/shared/ab-blake3/src/const_fn/tests.rs, crates/shared/ab-blake3/src/lib.rs
This essentially extracts https://github.com/BLAKE3-team/BLAKE3
This is just a beginning though. Either this version will be refactored or another created that works with `u32` words instead of bytes, so it works on GPU too.
Probably separately another version will be created that only offers API that can has up to a single block worth of data (64 bytes), which is actually a pretty common scenario, used in Merkle Trees, Chia PoSpace and other parts of consensus. Eventually there should be APIs that offer https://github.com/BLAKE3-team/BLAKE3/issues/478, which will accelerate Merkle Trees to new heights.
Either way this is a start, and while not used in this PR, should be very soon.
P.S. I tried to make it `no-panic`, but the rabbit hole went a bit too deep for the initial attempt, so …
=> Initial version of `ab-blake3` crate with `const fn` functions

Cargo.lock, Cargo.toml, crates/contracts/core/ab-contracts-common/Cargo.toml, crates/contracts/core/ab-contracts-common/src/method.rs, crates/shared/ab-blake3/Cargo.toml, crates/shared/ab-blake3/src/const_fn.rs, crates/shared/ab-blake3/src/const_fn/hazmat.rs, crates/shared/ab-blake3/src/const_fn/platform.rs, crates/shared/ab-blake3/src/const_fn/portable.rs, crates/shared/ab-blake3/src/const_fn/tests.rs, crates/shared/ab-blake3/src/lib.rs, crates/shared/ab-blake3/src/platform.rs, crates/shared/ab-blake3/src/portable.rs, crates/shared/ab-blake3/src/single_block.rs, crates/shared/ab-blake3/src/single_block/tests.rs, crates/shared/ab-blake3/src/single_chunk.rs, crates/shared/ab-blake3/src/single_chunk/tests.rs, crates/shared/ab-merkle-tree/Cargo.toml, crates/shared/ab-merkle-tree/src/balanced.rs, crates/shared/ab-merkle-tree/src/lib.rs, crates/shared/ab-merkle-tree/src/mmr.rs, crates/shared/ab-merkle-tree/src/unbalanced.rs, crates/shared/ab-merkle-tree/tests/balanced.rs, crates/shared/ab-merkle-tree/tests/unbalanced.rs, crates/shared/ab-proof-of-space/Cargo.toml, crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/shim.rs, subspace/Cargo.lock
This extends `ab-blake3` with a substantial number of additional public functions:
* single-chunk hashing
* single-block hashing
* single-block hashing of words (useful for GPU)
I also switched to `ab-blake3` in performance-sensitive crates and got some measurable speed-ups.
Merkle Tree before:
```
65536/balanced/new      time:   [4.1899 ms 4.1903 ms 4.1919 ms]
65536/balanced/compute-root-only
time:   [4.2740 ms 4.2743 ms 4.2754 ms]
65536/balanced/all-proofs
time:   [1.4789 ns 1.4796 ns 1.4824 ns]
65536/balanced/verify   time:   [70.688 ms 70.696 ms 70.728 ms]
```
Merkle Tree after:
```
65536/balanced/new      time:   [3.8788 ms 3.8789 ms 3.8790 ms]
65536/balanced/compute-root-only
time:   [3.6719 ms 3.6851 ms 3.6884 ms]
65536/balanced/all-proofs
time:   [1.4212 ns 1.4222 ns 1.4225 ns] …
```
=> Extend `ab-blake3` with additional functions

Cargo.lock, Cargo.toml, crates/farmer/ab-proof-of-space-gpu/Cargo.toml, crates/farmer/ab-proof-of-space-gpu/src/lib.rs, crates/farmer/ab-proof-of-space-gpu/src/shader.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/chacha8.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/chacha8/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1/cpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn/cpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num/u32.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num/u64.rs, crates/shared/ab-blake3/Cargo.toml, crates/shared/ab-blake3/src/lib.rs, crates/shared/ab-blake3/src/portable.rs, crates/shared/ab-blake3/src/single_block.rs, crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/chiapos/tables.rs
One more component necessary for plotting on GPU. A lot of workarounds and some upstream fixes were necessary to get to this point. There are still more bits and pieces missing, but this is a good progress.
Key things missing:
* sorting (might be possible to use a crate from crates.io)
* matching
* erasure coding
* combining it all into some usable public API
Any of those can _technically_ be done on CPU, but will be wildly inefficient due to excessive memory copies.
=> Implement `compute_fn()` in `ab-proof-of-space-gpu`

Cargo.lock, Cargo.toml, crates/node/ab-client-api/src/lib.rs, crates/node/ab-client-database/Cargo.toml, crates/node/ab-client-database/src/lib.rs, crates/node/ab-client-database/src/storage_backend.rs, crates/node/ab-client-database/src/storage_backend_adapter.rs, crates/node/ab-client-database/src/storage_item.rs, crates/node/ab-client-database/src/storage_item/block.rs, crates/node/ab-client-database/src/storage_item/page_group_header.rs, crates/shared/ab-core-primitives/src/block/header/owned.rs
This is in many ways incomplete and probably broken, but I need to get it out of the door.
This implements `ab-client-api` persistence APIs and is designed with abstract storage backend that persists data in aligned 4 kiB pages.
The idea of this design is to have purpose-built database that maps nicely onto modern SSDs (in the future page size may be increased to 16 kiB if it helps with performance and write amplification). See https://abundance.build/blog/2025-07-20-sparse-merkle-tree-and-client-database-preparation/#client-database for background information.
Things currently missing (but not critical at this stage):
* block pruning from memory (bodies are pruned, but headers are stored forever)
* page pruning (storage backend will inevitably run out of space until old pages can be …
=> Initial prototype of `ab-client-database`

crates/shared/ab-merkle-tree/benches/merkle_tree.rs, crates/shared/ab-merkle-tree/src/balanced.rs, crates/shared/ab-merkle-tree/src/lib.rs, crates/shared/ab-merkle-tree/tests/balanced.rs
Similarly to https://github.com/nazar-pc/abundance/pull/345, massive wins here again both for Merkle Tree root computation and archiving (which uses it) benchmarks:
```
Before:
65536/balanced/compute-root-only
time:   [4.0835 ms 4.0836 ms 4.0841 ms]
After:
65536/balanced/compute-root-only
time:   [555.84 µs 556.90 µs 557.80 µs]
Before:
segment-archiving-whole-segment
time:   [1.8868 s 1.8892 s 1.8914 s]
After:
segment-archiving-whole-segment
time:   [950.64 ms 957.24 ms 962.52 ms]
```
This is all on a single core. And archiving can be optimized further by making erasure coding more efficient and when BLAKE3 APIs are improved. Not to mention potential GPU acceleration.
Above benchmark is single-threaded, for context, single-threaded Subspace:
```
segment-archiving-whole-segment
time: …
```
=> Optimize `BalancedMerkleTree::compute_root_only()` using SIMD

Cargo.lock, crates/node/ab-client-api/src/lib.rs, crates/node/ab-client-block-authoring/src/slot_worker.rs, crates/node/ab-client-block-builder/Cargo.toml, crates/node/ab-client-block-builder/src/beacon_chain.rs, crates/node/ab-client-block-builder/src/lib.rs, crates/node/ab-client-block-import/Cargo.toml, crates/node/ab-client-block-import/src/beacon_chain.rs, crates/node/ab-client-block-import/src/lib.rs, crates/node/ab-client-consensus-common/Cargo.toml, crates/node/ab-client-consensus-common/src/lib.rs, crates/node/ab-client-consensus-common/src/state.rs, crates/node/ab-client-database/src/lib.rs, crates/shared/ab-merkle-tree/src/sparse.rs, crates/shared/ab-merkle-tree/tests/sparse.rs
This introduces a very naive state root computation mechanism. It is not efficient at all and will have to be completely rewritten down the line, but it should make it possible to integrate block execution into the codebase and make some progress on the overall block production/import workflow.
State management has proven to be a challenging problem, so I'm kicking it down the road for now.
=> Naive state root computation

Cargo.lock, crates/shared/ab-proof-of-space/Cargo.toml, crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/chiapos/table/tests.rs, crates/shared/ab-proof-of-space/src/chiapos/table/types.rs, crates/shared/ab-proof-of-space/src/chiapos/tables.rs, crates/shared/ab-proof-of-space/src/lib.rs, specs/00-subspace-diff.md
This is a major re-architecture of how Proof-of-Space is implemented.
It sacrifices the completeness of the tables for high-performance parallel processing, which is already faster on the CPU and will be very beneficial for GPU implementation as well. See subspace diff document for brief details, I'll also write a blog post describing the changed in more detail.
As the result, table creation is substantially faster, there are less allocations, memory usage has also decreased substantially, probably up to 80%.
The previous best observed result for parallel table construction was:
```
chia/table/parallel/8x  time:   [677.60 ms 684.25 ms 692.06 ms]
thrpt:  [11.560  elem/s 11.692  elem/s 11.806  elem/s]
```
With this PR performance is much higher:
```
chia/table/parallel/8x  time:   [543.21 …
```
=> PoS buckets

crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/chiapos/table/rmap.rs, subspace/Cargo.lock
`rmap` is a key data structure for finding matches. Unfortunately, it was quite large:
> PARAM_BC * size_of::<[Position; 2]>() = 15113 * 8 = 120904 bytes
While not a huge issue for CPU, it is still large enough to not fit into L1 CPU cache. The situation is even worse on GPUs, where it is extremely desirable to keep hot data in shared memory, which is also very small (~32 kiB on older GPUs, could be 64 kiB or larger on latest GPUs).
This PR exploits the fact that while the number of slots in `rmap` is 15113, the actual number of elements is upper-bound by a constant 272. So we can create two maps: one small map with 15113 small 16-bit pointers (I tried making it even smaller with 9-bit pointers, but on CPU it becomes slightly slower than larger `rmap` rather than faster, might be …
=> PoS smaller rmap

crates/farmer/ab-proof-of-space-gpu/build.rs, crates/farmer/ab-proof-of-space-gpu/src/shader.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/chacha8.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/chacha8/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn/gpu_tests.rs, crates/shared/ab-proof-of-space/src/chiapos/table.rs
This prepares for more separation between two shader builds. It is no longer about supporting or not supporting `u64`, but also shared memory size and potentially some other features.
Modern version will assume relatively modern GPUs with 32 kiB+ of shared memory, the fallback version will work fine on baseline 16 kiB too, although with reduced performance.
There are also some cleanups included here.
Not in this PR, but Vulkan version requirements will also increase to 1.3 (for both variants) in order to support compact and efficient implementation using subgroup intrinsics of rust-gpu.
=> Modern/fallback GPU shaders

crates/farmer/ab-proof-of-space-gpu/Cargo.toml, crates/farmer/ab-proof-of-space-gpu/build.rs, crates/farmer/ab-proof-of-space-gpu/src/lib.rs, crates/farmer/ab-proof-of-space-gpu/src/shader.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/chacha8/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/constants.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets/cpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets/rmap.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets/rmap/tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/types.rs, crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/chiapos/table/tests.rs
This is a GPU implementation for `find_matches_in_buckets`.
I had to jump through a lot of hoops to get it to compile and there is tons of TODOs in all new files that should eventually be cleaned up. But I did get it to compile and run in the end.
This introduces more differences between compiled shader variants. The modern version expects 32 kiB of shared memory and will store `Rmap` there, while fallback version will use global memory for this purpose. Otherwise they are very similar and runtime detection will pick the right version. There is no handling of completely unsupported GPUs, but I think it is fine for tests and will be implemented in non-test code.
The next step is to implement bucketing logic, which I think I'll start by experimenting some more with CPU version since I think …
=> Implement `find_matches_in_buckets` shader for GPU

crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/chiapos/table/rmap.rs, crates/shared/ab-proof-of-space/src/chiapos/table/tests.rs, crates/shared/ab-proof-of-space/src/chiapos/table/types.rs, crates/shared/ab-proof-of-space/src/chiapos/tables.rs
I looked at buckets recently and noticed that especially after recent refactoring random lookups for `y` needed during both tables creation and proving are actually happening in sync with reading corresponding positions. Since reading positions without reading `y`s is not really happening, why not storing both together?
Moreover, storing full `y` is not actually necessary, we could store just `r` and do cheap addition based on a bucket value is in, but it ended up being a tiny bit slower from my testing (but it would use a bit less memory).
With a sprinkle of cache alignment for `LeftTargets` we have another major performance improvement and I think that actually sorting revisit might be happening soon, but this time using a custom radix sort implementation.
Results are still a bit flaky, …
=> Improve PoS performance with better data layout

crates/farmer/ab-farmer-components/benches/auditing.rs, crates/farmer/ab-farmer-components/benches/plotting.rs, crates/farmer/ab-farmer-components/benches/proving.rs, crates/farmer/ab-farmer-components/benches/reading.rs, crates/farmer/ab-farmer-components/src/plotting.rs, crates/farmer/ab-farmer-components/src/reading.rs, crates/shared/ab-proof-of-space/Cargo.toml, crates/shared/ab-proof-of-space/benches/pos.rs, crates/shared/ab-proof-of-space/src/chia.rs, crates/shared/ab-proof-of-space/src/chiapos.rs, crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/chiapos/table/rmap.rs, crates/shared/ab-proof-of-space/src/chiapos/table/rmap/tests.rs, crates/shared/ab-proof-of-space/src/chiapos/table/tests.rs, crates/shared/ab-proof-of-space/src/chiapos/table/types.rs, crates/shared/ab-proof-of-space/src/chiapos/tables.rs, crates/shared/ab-proof-of-space/src/chiapos/tables/tests.rs, crates/shared/ab-proof-of-space/src/lib.rs, crates/shared/ab-proof-of-space/src/shim.rs, subspace/crates/subspace-farmer/src/bin/subspace-farmer/commands/benchmark.rs, subspace/crates/subspace-farmer/src/plotter/cpu.rs, subspace/crates/subspace-farmer/src/single_disk_farm/farming.rs, subspace/crates/subspace-farmer/src/single_disk_farm/piece_reader.rs, subspace/shared/subspace-proof-of-space-gpu/src/cuda/tests.rs, subspace/shared/subspace-proof-of-space-gpu/src/rocm/tests.rs
A bunch of optimizations here:
* better cleanup for unused memory using new `PrunedTable` abstraction and some fixes
* faster proof verification without heap allocations
* refactored features in `ab-proof-of-space` and fixes to make crate actually usable without `alloc`
* `LeftTargets` is now reused across multiple table generator instances
* table generator instances take `&self` rather than `&mut self` and are cheap to clone, which makes them much easier to use and doesn't require locks for shared access
Verification performance change:
```
Before:
chia/verification       time:   [7.0819 µs 7.0908 µs 7.0961 µs]
thrpt:  [140.92 Kelem/s 141.03 Kelem/s 141.21 Kelem/s]
After:
chia/verification       time:   [6.4624 µs 6.4689 µs 6.4758 µs]
thrpt:  [154.42 Kelem/s 154.59 Kelem/s 154.74 …
```
=> Optimize CPU PoS

Cargo.lock, crates/farmer/ab-proof-of-space-gpu/Cargo.toml, crates/farmer/ab-proof-of-space-gpu/build.rs, crates/farmer/ab-proof-of-space-gpu/src/lib.rs, crates/farmer/ab-proof-of-space-gpu/src/shader.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1/cpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/constants.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets/cpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets/rmap.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/sort_buckets.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/sort_buckets/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/types.rs, crates/shared/ab-proof-of-space/src/chiapos.rs, crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/chiapos/table/rmap.rs
First of all, `f1()` shader was modified to write output straight into intended buckets rather than doing data movement with a separate shader. The order in buckets is undefined due to use of global atomic increments.
Second, `sort_buckets()` shader is implemented that implements bitonic sort to fix up order within bucket after shaders like `f1()` wrote their output.
With these all that is left is to combine find_matches with compute_fn into a single shader for efficiency and have another shader that can find proofs and apply them to record chunks. With that an initial implementation of GPU plotting will be complete.
=> Sort buckets shader

crates/farmer/ab-proof-of-space-gpu/build.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/sort_buckets.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/sort_buckets/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/types.rs
This should be quite awesome performance-wise, though is very hard to understand. Thankfully there are tests to ensure correctness.
=> Optimize `sort_buckets` shader with only using subgroup operations

.github/workflows/rust.yml
It was not difficult to add, though it blows up the job matrix a bit. Aarch64 runner is also faster than x86-64, so it is tempting to disable x86-64 runner, but that is the most popular target, so...
=> Add aarch64 Windows to CI

.github/workflows/rust.yml, crates/farmer/ab-proof-of-space-gpu/src/shader.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/chacha8/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn/cpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/constants.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_and_compute_fn.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_and_compute_fn/cpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_and_compute_fn/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets/cpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_in_buckets/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/sort_buckets.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/sort_buckets/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/types.rs, crates/shared/ab-proof-of-space/src/chiapos.rs, crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/chiapos/tables.rs
This implement a shader that is a combination of existing `find_matches_in_buckets` and `compute_fn` shader.
Combining them is much more efficient because matches found in a bucket can be turned into `y` values and metadata with `compute_fn` using shared memory without writing to the global memory first.
For the same reason `chacha8` shader will be integrated into `compute_f1` shader next.
Table creation on GPU is now basically complete. The only remaining shader is one that that finds proofs and applies them to record chunks (most likely a single shader for the same reason as fusion of the other shaders.
With that remains is to combine these shaders into a complete pipeline for plotting purposes and integrating it into the farmer.
There is also a minor memory usage reduction change here …
=> Implement `find_matches_and_compute_fn` shader

crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/find_matches_and_compute_fn.rs, crates/shared/ab-proof-of-space/benches/pos.rs, crates/shared/ab-proof-of-space/src/chia.rs, crates/shared/ab-proof-of-space/src/chiapos.rs, crates/shared/ab-proof-of-space/src/chiapos/tables.rs, crates/shared/ab-proof-of-space/src/lib.rs, specs/00-subspace-diff.md
All commits except last are minor refactoring and preparation.
The last commit is based on the observation that proofs are searched for essentially 32-bit challenge indices (only 16 of which are ever occupied due to s-bucket sizes), but due to the fact that challenge was converted into big endian, nearby indices actually hit different and not even adjacent buckets: 0, 17, 34, 52, 69...
That wasn't great for spatial locality and potential SIMD usage. The bucketing can and will change in upcoming PR and while doing so it is possible to make bucketing such that it'll cluster the values in a way that makes them close for big-endian challenge indices, since there is no goal to make it Subspace-compatible, a simpler strategy is chosen instead. For Subspace backport, the bucketing in upcoming PR …
=> Change the way challenge indices are interpreted to improve spatial locality during proof searching

crates/farmer/ab-farmer-components/benches/proving.rs, crates/farmer/ab-farmer-components/benches/reading.rs, crates/farmer/ab-farmer-components/src/proving.rs, crates/farmer/ab-farmer-components/src/reading.rs, subspace/crates/subspace-farmer/src/bin/subspace-farmer/commands/benchmark.rs, subspace/crates/subspace-farmer/src/bin/subspace-farmer/commands/cluster/farmer.rs, subspace/crates/subspace-farmer/src/bin/subspace-farmer/commands/farm.rs, subspace/crates/subspace-farmer/src/bin/subspace-farmer/commands/shared.rs, subspace/crates/subspace-farmer/src/single_disk_farm.rs, subspace/crates/subspace-farmer/src/single_disk_farm/farming.rs, subspace/crates/subspace-farmer/src/single_disk_farm/piece_reader.rs
While it may help certain SSDs with proving, it is very rarely needed and for SSDs of meaningful size will likely still be somewhat problematic during auditing.
This was a useful experiment at a time, but it is probably time to let it go.
=> Remove `ReadSectorRecordChunksMode`

crates/farmer/ab-farmer-components/src/auditing.rs, crates/farmer/ab-farmer-components/src/plotting.rs, crates/farmer/ab-farmer-components/src/proving.rs, crates/farmer/ab-farmer-components/src/reading.rs, crates/farmer/ab-farmer-components/src/sector.rs, crates/shared/ab-proof-of-space/src/chia.rs, crates/shared/ab-proof-of-space/src/chiapos/table.rs, crates/shared/ab-proof-of-space/src/chiapos/table/tests.rs, crates/shared/ab-proof-of-space/src/lib.rs, subspace/crates/subspace-farmer/src/plotter/gpu/cuda.rs, subspace/crates/subspace-farmer/src/plotter/gpu/rocm.rs, subspace/shared/subspace-proof-of-space-gpu/src/cuda/tests.rs, subspace/shared/subspace-proof-of-space-gpu/src/rocm/tests.rs
I observed some time ago that all chunks in a sector end up being encoded. As such, support for unencoded chunks that do not actually exist results in unnecessary complexity and performance overhead.
Here I added a test case that ensures current parameters produce enough proofs to encode the whole sector (the math behind probabilities was generated by LLM and I don't have 100% confidence in it, but the number of proofs is so large, it seems plausible).
This simplification will be helpful for further optimizations, especially with GPU plotting.
=> Only encoded sector chunks

crates/shared/ab-core-primitives/src/pos.rs
I incorrectly read the size of the data structure as bits instead of bytes before. It clearly doesn't fit into a single block, but it will fit into a single chunk even if `k` is increased.
=> Fix wrong function usage
