nazar-pc/abundance

website/book/book.toml, website/book/src/Execution_environment/Contracts_overview.md, website/book/src/SUMMARY.md, website/main/assets/css/custom.css, website/main/content/_index.md
The biggest change here is contracts overview in the book with some diagrams
=> Contracts overview in the book

crates/contracts/ab-contract-example/src/lib.rs, crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-io-type/src/lib.rs, crates/contracts/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/ab-contracts-io-type/src/trivial_type.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-macros/src/contract/methods.rs, rustfmt.toml, website/book/book.toml
This updates code to 2024 edition and makes a few fixes/improvements
=> Various updates

crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-io-type/src/lib.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-macros/src/contract.rs, crates/contracts/ab-contracts-macros/src/contract/methods.rs, crates/contracts/ab-system-contract-code/src/lib.rs
Metadata is simplified, shouldn't make a huge difference, especially after compression
=> Metadata improvements

crates/contracts/ab-contract-example/Cargo.toml, crates/contracts/ab-contracts-common/Cargo.toml, crates/contracts/ab-contracts-io-type/Cargo.toml, crates/contracts/ab-contracts-macros/Cargo.toml, crates/contracts/ab-contracts-macros/src/contract.rs, crates/contracts/ab-contracts-macros/src/contract/init.rs, crates/contracts/ab-contracts-macros/src/contract/methods.rs, crates/contracts/ab-contracts-macros/src/contract/update.rs, crates/contracts/ab-contracts-macros/src/contract/view.rs, crates/contracts/ab-contracts-standards/Cargo.toml, crates/contracts/ab-contracts-trivial-type-derive/Cargo.toml, crates/contracts/ab-contracts-trivial-type-derive/src/lib.rs, crates/contracts/ab-system-contract-address-allocator/Cargo.toml, crates/contracts/ab-system-contract-code/Cargo.toml, crates/contracts/ab-system-contract-state/Cargo.toml
https://github.com/nazar-pc/abundance/pull/18 didn't change edition for code, this actually does it
=> 2024 edition with some minor fixes

crates/contracts/ab-contracts-common/src/env.rs, crates/contracts/ab-contracts-common/src/lib.rs
Minor refactoring and typo corrections
=> Env refactoring

crates/contracts/ab-contract-example/Cargo.toml, crates/contracts/ab-contracts-common/Cargo.toml, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-macros-impl/src/contract.rs, crates/contracts/ab-contracts-macros-impl/src/contract/method.rs, crates/contracts/ab-system-contract-address-allocator/Cargo.toml, crates/contracts/ab-system-contract-code/Cargo.toml, crates/contracts/ab-system-contract-state/Cargo.toml
This should be one of the last PRs before introducing native contracts executor
=> Contracts infrastructure refactoring

Cargo.lock, crates/contracts/ab-contract-example/Cargo.toml, crates/contracts/ab-contract-example/src/lib.rs, crates/contracts/ab-contracts-common/Cargo.toml, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-common/src/metadata/decode.rs, crates/contracts/ab-contracts-io-type/src/lib.rs, crates/contracts/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/ab-contracts-io-type/src/trivial_type.rs, crates/contracts/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/ab-contracts-macros-impl/src/contract/method.rs, crates/contracts/ab-contracts-macros/Cargo.toml, crates/contracts/ab-contracts-macros/src/__private.rs, crates/contracts/ab-system-contract-address-allocator/Cargo.toml, crates/contracts/ab-system-contract-address-allocator/src/lib.rs, crates/contracts/ab-system-contract-code/Cargo.toml, crates/contracts/ab-system-contract-state/Cargo.toml
Assortment of various fixes and improvements I have noticed while trying to run still incomplete native executor. It mostly kind of works, but not fully, hence not included in this PR.
=> A bunch of fixes

crates/contracts/ab-contracts-executor/src/lib.rs
This makes code much easier to read. Also fixes `ArgumentKind::Output`'s usage of `*const u8` instead of correct `*mut u8` for data input.
=> Simplify executor boilerplate

crates/contracts/ab-contracts-executor/src/lib.rs, website/book/src/Execution_environment/Contracts_overview.md, website/book/src/How/Consensus.md
Most of these expand on existing topics with clarifications and examples based on feedback from Shamil
=> Documentation updates

crates/contracts/ab-contract-example-ft/src/lib.rs, crates/contracts/ab-contract-playground/src/lib.rs, crates/contracts/ab-contracts-common/src/lib.rs, crates/contracts/ab-contracts-executor/src/context.rs, crates/contracts/ab-contracts-executor/src/context/ffi_call.rs, crates/contracts/ab-contracts-executor/src/slots.rs, website/book/src/Execution_environment/Contracts_overview.md
Minor things accumulated in the local branch so far
=> Minor improvements

Cargo.lock, crates/contracts/ab-contract-example-ft/src/lib.rs, crates/contracts/ab-contract-example-ft/tests/basic.rs, crates/contracts/ab-contract-playground/src/lib.rs, crates/contracts/ab-contract-playground/tests/basic.rs, crates/contracts/ab-contracts-executor/src/aligned_buffer.rs, crates/contracts/ab-contracts-executor/src/context/ffi_call.rs, crates/contracts/ab-contracts-executor/src/slots.rs, crates/contracts/ab-contracts-io-type/Cargo.toml, crates/contracts/ab-contracts-io-type/src/lib.rs, crates/contracts/ab-contracts-macros-impl/src/contract.rs, crates/contracts/ab-contracts-standards/src/fungible.rs, crates/contracts/ab-contracts-standards/src/lib.rs, website/book/src/Execution_environment/Contracts_overview.md
Another collection of minor changes extracted from local branch
=> Minor tweaks

.github/workflows/rust.yml, crates/contracts/ab-contracts-common/src/metadata/decode.rs, crates/contracts/ab-contracts-io-type/src/metadata/type_name.rs, crates/contracts/ab-contracts-macros-impl/src/lib.rs, rust-toolchain.toml
Also added testing on Linux aarch64 in CI
=> Update Rust toolchain

crates/contracts/ab-contract-example-wallet/tests/flip.rs
Takes quite a while under Miri, this should help
=> Reduce the number of iterations in a test

crates/contracts/core/ab-contracts-executor/src/context.rs, crates/contracts/core/ab-contracts-executor/src/context/ffi_call.rs
This improves performance of https://github.com/nazar-pc/abundance/pull/103 further:
```
flipper/direct          time:   [77.357 ns 77.609 ns 77.909 ns]
thrpt:  [12.835 Melem/s 12.885 Melem/s 12.927 Melem/s]
flipper/transaction     time:   [92.766 ns 93.097 ns 93.498 ns]
thrpt:  [10.695 Melem/s 10.741 Melem/s 10.780 Melem/s]
```
There are also a few small fixes and improves docs.
=> Performance tuning

crates/contracts/core/ab-contracts-common/src/env.rs, crates/contracts/core/ab-contracts-executor/src/aligned_buffer.rs, crates/contracts/core/ab-contracts-executor/src/context/ffi_call.rs, crates/contracts/core/ab-contracts-executor/src/lib.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/lib.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload/builder.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/payload/builder/tests.rs
There is an assortment of optimizations and simplifications that all add up to a minor, but measurable performance boost
=> Optimizations

crates/contracts/core/ab-contracts-executor/src/context/ffi_call.rs
This further reduces overhead substantially:
```
flipper/direct          time:   [54.646 ns 54.784 ns 54.945 ns]
thrpt:  [18.200 Melem/s 18.253 Melem/s 18.299 Melem/s]
flipper/transaction     time:   [64.194 ns 64.384 ns 64.603 ns]
thrpt:  [15.479 Melem/s 15.532 Melem/s 15.578 Melem/s]
time:   [574.31 ns 576.54 ns 579.13 ns]
thrpt:  [1.7267 Melem/s 1.7345 Melem/s 1.7412 Melem/s]
```
=> Improve `make_ffi_call` performance by avoiding heap allocation for `delayed_processing`

crates/contracts/core/ab-contracts-executor/src/lib.rs, crates/contracts/core/ab-contracts-slots/src/aligned_buffer.rs
Some TODOs are no longer relevant, some comments were outdated
=> Small cleanups

Cargo.lock, crates/contracts/core/ab-contracts-io-type/src/metadata/type_details.rs, crates/contracts/core/ab-contracts-io-type/src/variable_bytes.rs, crates/contracts/core/ab-contracts-io-type/src/variable_elements.rs, crates/contracts/core/ab-contracts-slots/src/slots.rs, crates/contracts/example/ab-example-contract-wallet/Cargo.toml, crates/contracts/example/ab-example-contract-wallet/src/lib.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/Cargo.toml, crates/contracts/system/ab-system-contract-simple-wallet-base/src/lib.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/utils.rs, crates/contracts/system/ab-system-contract-state/src/lib.rs
Typical usage encapsulated into helper functions, while also switching APIs to use stricter types for easier composition on higher level. Some APIs improved/extended in the process.
=> Simplify wallet creation

website/main/content/blog/2025-03-31-hierarchical-subspace-protocol/index.md
Fix the (hopefully) last broken image.
=> 2025-03-31: fix broken image

Cargo.lock, Cargo.toml, crates/contracts/core/ab-contracts-common/src/address.rs, crates/contracts/core/ab-contracts-macros-impl/src/contract/method.rs, crates/contracts/system/ab-system-contract-code/src/lib.rs, crates/contracts/system/ab-system-contract-native-token/Cargo.toml, crates/contracts/system/ab-system-contract-native-token/src/lib.rs, crates/contracts/system/ab-system-contract-native-token/tests/basic.rs, crates/contracts/system/ab-system-contract-simple-wallet-base/src/utils.rs, crates/execution/ab-executor-native/Cargo.toml, crates/execution/ab-executor-native/src/lib.rs
Basic version of the native token system contract.
Minor change to code contract allows to deploy system contracts by execution environment without pretending that calls were made by the code contract itself.
=> Native token system contract

subspace/crates/pallet-subspace/src/lib.rs
No logic changes here, just moving code around
=> Extract solution range and PoT code in block initialization into dedicated functions

crates/contracts/core/ab-contract-playground/src/lib.rs, crates/contracts/core/ab-contracts-io-type/src/lib.rs, crates/contracts/core/ab-contracts-io-type/src/maybe_data.rs, crates/contracts/example/ab-example-contract-ft/src/lib.rs, crates/contracts/system/ab-system-contract-native-token/src/lib.rs, website/book/src/Execution_environment/Contracts_overview.md
Improvements based on developer interview with Colin
=> Small improvements

crates/execution/ab-executor-native/src/lib.rs
This will be helpful as more system contracts are added
=> Make system contracts initialization more compact

.github/workflows/rust.yml
There will be more crates with `no-panic` that will need to be checked
=> Upgrade CI with additional checks

subspace/Cargo.lock, subspace/crates/sc-consensus-subspace/Cargo.toml, subspace/crates/subspace-archiving/Cargo.toml, subspace/crates/subspace-archiving/src/archiver.rs, subspace/crates/subspace-archiving/src/lib.rs, subspace/crates/subspace-archiving/src/piece_reconstructor.rs, subspace/crates/subspace-archiving/src/reconstructor.rs, subspace/crates/subspace-erasure-coding/Cargo.toml, subspace/crates/subspace-erasure-coding/src/lib.rs, subspace/crates/subspace-farmer-components/Cargo.toml, subspace/crates/subspace-farmer-components/src/reading.rs, subspace/crates/subspace-service/Cargo.toml, subspace/shared/subspace-data-retrieval/Cargo.toml
Better APIs, slightly better performance too
=> Archiver erasure coding refactoring

subspace/crates/subspace-farmer/src/cluster/controller.rs, subspace/crates/subspace-farmer/src/cluster/controller/caches.rs, subspace/crates/subspace-farmer/src/cluster/controller/farms.rs, subspace/crates/subspace-farmer/src/cluster/controller/stream_map.rs
This is a backport of https://github.com/autonomys/subspace/pull/3489
=> fix: cache not detected when farmer is run in cluster mode

subspace/crates/subspace-farmer/src/bin/subspace-farmer/commands/benchmark.rs, subspace/crates/subspace-networking/src/node.rs, subspace/crates/subspace-networking/src/protocols/request_response/request_response_factory.rs, subspace/crates/subspace-networking/src/utils/piece_provider.rs
This backports https://github.com/autonomys/subspace/pull/3493 and https://github.com/autonomys/subspace/pull/3494 cosmetic changes
=> Backport patches from Subspace

subspace/crates/pallet-subspace/src/lib.rs, subspace/crates/pallet-subspace/src/mock.rs, subspace/crates/sc-consensus-subspace/src/block_import.rs, subspace/crates/sc-consensus-subspace/src/slot_worker.rs, subspace/crates/sc-consensus-subspace/src/verifier.rs, subspace/crates/sc-proof-of-time/src/source.rs, subspace/crates/sp-consensus-subspace/src/digests.rs, subspace/crates/sp-consensus-subspace/src/lib.rs
Small follow-up to https://github.com/nazar-pc/abundance/pull/223 that removes a few more enum variants that I don't think will be necessary
=> Enum variant cleanups

Cargo.lock, Cargo.toml, crates/shared/ab-archiving/src/archiver.rs, crates/shared/ab-core-primitives/Cargo.toml, subspace/Cargo.lock, subspace/Cargo.toml, subspace/crates/pallet-subspace/src/mock.rs, subspace/crates/subspace-farmer/src/bin/subspace-farmer/commands/shared/network.rs, subspace/crates/subspace-networking/src/node.rs, subspace/crates/subspace-networking/src/node_runner.rs, subspace/crates/subspace-networking/src/protocols/request_response/handlers/generic_request_handler.rs, subspace/crates/subspace-networking/src/utils.rs, subspace/crates/subspace-networking/src/utils/piece_provider.rs, subspace/crates/subspace-runtime/Cargo.toml, subspace/crates/subspace-service/src/metrics.rs, subspace/crates/subspace-service/src/sync_from_dsn.rs, subspace/crates/subspace-service/src/sync_from_dsn/import_blocks.rs, subspace/crates/subspace-service/src/sync_from_dsn/segment_header_downloader.rs
A few relevant fixes and minor changes
=> Backport Subspace fixes

subspace/crates/subspace-proof-of-space/benches/pos.rs
Updated shim test in https://github.com/nazar-pc/abundance/commit/de8e6027a2a4c35cc550201db2172b7525d3f7a6, but forgot to update shim benchmark
=> Fix PoSpace benchmark

crates/shared/ab-core-primitives/src/pot.rs, crates/shared/ab-core-primitives/src/shard.rs, crates/shared/ab-core-primitives/src/solutions.rs, crates/shared/ab-trivial-type-derive/src/lib.rs, subspace/crates/pallet-subspace/src/lib.rs, subspace/crates/pallet-subspace/src/mock.rs, subspace/crates/sc-consensus-subspace/src/block_import.rs, subspace/crates/sc-consensus-subspace/src/slot_worker.rs, subspace/crates/sc-proof-of-time/src/source/state.rs, subspace/crates/sc-proof-of-time/src/verifier.rs, subspace/crates/sc-proof-of-time/src/verifier/tests.rs, subspace/crates/sp-consensus-subspace/src/lib.rs, subspace/crates/subspace-farmer-components/src/lib.rs, subspace/crates/subspace-farmer-components/src/proving.rs
Some refactoring extracted from local branch while working on block format.
PoT parameters change and shard index in solution will be needed for block header later.
=> Core primitives refactoring

crates/contracts/system/ab-system-contract-simple-wallet-base/src/seal.rs, crates/shared/ab-core-primitives/src/address.rs, crates/shared/ab-core-primitives/src/hashes.rs, crates/shared/ab-core-primitives/src/pieces.rs, crates/shared/ab-core-primitives/src/pot.rs, crates/shared/ab-core-primitives/src/solutions.rs, crates/shared/ab-core-primitives/src/transaction.rs, website/main/content/blog/2025-05-12-address-formatting.md
Assortment of small things extracted from a local branch
=> Minor cleanups

crates/shared/ab-aligned-buffer/src/lib.rs, crates/shared/ab-aligned-buffer/src/tests.rs
=> Implement reallocation in `OwnedAlignedBuffer`

website/book/src/Contribute.md
Also added notes whether research or engineering is needed for each section
=> Update "Contribute" page with shard assignment

crates/node/ab-client-proof-of-time/src/source.rs, crates/shared/ab-proof-of-time/src/lib.rs, subspace/Cargo.lock, subspace/crates/sc-consensus-subspace-rpc/Cargo.toml, subspace/crates/sc-consensus-subspace-rpc/src/lib.rs, subspace/crates/sc-consensus-subspace/src/slot_worker.rs, subspace/crates/subspace-service/src/lib.rs, subspace/crates/subspace-service/src/rpc.rs
This reduces dependency on Substrate types and infrastructure in `sc-consensus-subspace` and `sc-consensus-subspace-rpc`
=> Consensus refactoring

Cargo.lock, Cargo.toml, crates/node/ab-client-api/src/lib.rs, crates/node/ab-client-block-authoring/Cargo.toml, crates/node/ab-client-block-authoring/src/lib.rs, crates/node/ab-client-block-authoring/src/slot_worker.rs, crates/node/ab-client-block-builder/Cargo.toml, crates/node/ab-client-block-builder/src/lib.rs, crates/node/ab-client-block-import/Cargo.toml, crates/node/ab-client-block-import/src/lib.rs, crates/node/ab-client-block-import/src/segment_headers_store.rs, specs/00-subspace-diff.md, subspace/Cargo.lock, subspace/crates/sc-consensus-subspace/src/slot_worker.rs
Based on `sc-consensus-subspace` with some modifications. Except for slot worker, which largely looks like what it should be, the rest are just interfaces and will need concrete implementations before slot worker is usable for anything.
=> Introduce prototypes of infrastructure crates related to block creation and processing

Cargo.lock, crates/shared/ab-archiving/Cargo.toml, crates/shared/ab-io-type/Cargo.toml, crates/shared/ab-merkle-tree/Cargo.toml, crates/shared/ab-merkle-tree/benches/merkle_tree.rs, crates/shared/ab-merkle-tree/tests/balanced_hashed.rs, crates/shared/ab-trivial-type-derive/Cargo.toml
This will help with future refactoring to ensure performance only improves from here
=> Merkle Tree benchmarks

website/main/content/blog/2025-06-16-thinking-about-security.md
@nazar-pc, as we discussed sync, I haven't been able to fix the Latex rendering. Let me know if you need help there (and if you are able to fix it). Thanks!
=> 2025-06-16: status update

crates/farmer/ab-proof-of-space-gpu/src/lib.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/chacha8/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1/gpu_tests.rs
Several things were off here and there
=> Small GPU cleanups

Cargo.lock, Cargo.toml, crates/farmer/ab-proof-of-space-gpu/rust-gpu-workaround/Cargo.lock, crates/farmer/ab-proof-of-space-gpu/rust-gpu-workaround/Cargo.toml, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/constants.rs, subspace/Cargo.lock
Better, but not quite there yet
=> Upgrade `rust-gpu` to support better handling of constants

crates/farmer/ab-proof-of-space-gpu/src/shader/chacha8.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num/native.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num/u32.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num/u32/tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num/u64.rs
A few minor things extracted from local branch that will be used later in `compute_fn()`
=> GPU prototype updates

crates/shared/ab-merkle-tree/benches/merkle_tree.rs, crates/shared/ab-merkle-tree/src/balanced.rs, crates/shared/ab-merkle-tree/src/lib.rs, crates/shared/ab-merkle-tree/tests/balanced.rs, crates/shared/ab-merkle-tree/tests/unbalanced.rs
Extracted from local branch, made these while working on Sparse Merkle Tree
=> Merkle Tree refactoring

crates/farmer/ab-proof-of-space-gpu/src/lib.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num/native.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num/u32.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num/u32/tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/num/u64.rs
This fixes compilation on rust-gpu for AND/OR/XOR operations and uses more appropriate experimental APIs for add/sub, which should map to something better during codegen.
=> Int polyfills optimizations

crates/farmer/ab-farmer-components/src/segment_reconstruction.rs, crates/shared/ab-core-primitives/src/segments.rs, crates/shared/ab-data-retrieval/Cargo.toml, crates/shared/ab-data-retrieval/src/segment_downloading.rs, subspace/Cargo.lock, subspace/crates/sc-consensus-subspace/Cargo.toml, subspace/crates/sc-consensus-subspace/src/archiver.rs, subspace/crates/subspace-farmer/src/farmer_cache.rs, subspace/crates/subspace-networking/src/utils/piece_provider.rs, subspace/crates/subspace-service/src/sync_from_dsn.rs, subspace/crates/subspace-service/src/sync_from_dsn/import_blocks.rs, subspace/crates/subspace-service/src/sync_from_dsn/segment_header_downloader.rs, subspace/crates/subspace-service/src/sync_from_dsn/snap_sync.rs
Several PRs that might be relevant/useful
=> Subspace backports

Cargo.lock, crates/execution/ab-executor-native/src/lib.rs, crates/node/ab-client-api/Cargo.toml, crates/node/ab-client-api/src/lib.rs, crates/node/ab-client-block-import/src/beacon_chain.rs, crates/node/ab-client-block-import/src/importing_blocks.rs, crates/node/ab-client-block-import/src/lib.rs, crates/node/ab-client-database/src/lib.rs, crates/node/ab-client-database/src/page_group/block/block.rs, crates/node/ab-client-database/src/storage_backend_adapter/storage_item.rs, subspace/Cargo.lock
This primarily extends API with storing system contracts state. Execution of the block will be effectively split into two parts: system contracts will be handled first, validity of all transactions will also be checked, but actual transaction execution will happen some time before the next block is imported asynchronously.
Execution of system contracts as such was not added in this PR and will be implemented separately.
=> `ab-client-database` improvements

crates/node/ab-client-database/src/lib.rs
I don't think it ended up being needed, the only place where reference count is checked is on the tip and tips do not have child blocks, so this is only causing memory leak and nothing else (there is no pruning in the database more generally right now, but that is a separate issue and has TODOs).
=> Remove `OpaqueParentHeader`

.github/workflows/rust.yml
Looks like it'll not default to LLD otherwise
=> Specify LLD explicitly on Linux

crates/node/ab-node/src/storage_backend.rs, crates/shared/ab-blake3/src/single_block.rs
Only learned `array::each_ref()` exists earlier today, make the code much cleaner
=> Small code improvements

Cargo.lock, crates/farmer/ab-proof-of-space-gpu/Cargo.toml, crates/farmer/ab-proof-of-space-gpu/src/lib.rs, crates/farmer/ab-proof-of-space-gpu/src/shader.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1/cpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_f1/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn/cpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/compute_fn/gpu_tests.rs, crates/farmer/ab-proof-of-space-gpu/src/shader/types.rs, crates/shared/ab-proof-of-space/src/chiapos/table/types.rs
Preparation for upcoming changes
=> PoS GPU cleanups
